server:
  port: 8090

## ---------- circuit breaker configurations ------------ ##
resilience4j.circuitbreaker:
  circuitBreakerAspectOrder: 1
  instances:
    rest1lookup:
      registerHealthIndicator: true
      slidingWindowSize: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
    rest2lookup:
      registerHealthIndicator: true
      slidingWindowSize: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

## ----------- actuator configurations -------------- ##

management:
    health:
      circuitbreakers:
        enabled: true
    endpoints:
      web:
        exposure:
          include: health,metrics
    endpoint:
      health:
        show-details: always